### ISSUE TITLE
JRuby on Windows doesn't seem to work

### ISSUE THREAD

**Issue by slonopotamus** [eregon/use-ruby-action#12]
I [tried](https://github.com/slonopotamus/asciidoctor-epub3/commit/6d74e3cb4382185370cb760e29c6f55c5b3b50d2) using JRuby on Windows through use-ruby-action, but looks like [it hangs](https://github.com/slonopotamus/asciidoctor-epub3/runs/406590325). I'm not sure what exactly is going on there because `bundle install` step has finished, but next step that is supposed to run RSpec, doesn't contain any output at all.

**Comment by eregon** [comment]
Thanks for the report.
I would think this is either an issue of the workflow, GitHub Actions or JRuby but not this action since it's just using the tarball from the JRuby website.
But let's figure out nevertheless, and one can never be sure.

https://github.com/slonopotamus/asciidoctor-epub3/blob/6d74e3cb4382185370cb760e29c6f55c5b3b50d2/.github/workflows/ci.yml#L47-L48
is `bundle exec ruby -w $(bundle exec ruby -e "print Gem.bin_path 'rake', 'rake'") spec`.
This sounds unlikely to work in the default shell on windows, which is PowerShell.
I would suggest to try `bundle exec rake spec` with 
```yaml
        env:
          RUBYOPT: "-w"
```

Could you cancel that CI run? I think we might be able to see the logs once it's canceled/terminated.

Could you try running a single simple spec to see if maybe some spec causes hanging on JRuby on Windows?

**Comment by slonopotamus** [comment]
> I would suggest to try `bundle exec rake spec`

Tried, it also hangs:

https://github.com/slonopotamus/asciidoctor-epub3/runs/406603429

**Comment by slonopotamus** [comment]
> Could you cancel that CI run?

https://github.com/slonopotamus/asciidoctor-epub3/runs/406603429#step:6:4

**Comment by eregon** [comment]
https://github.com/slonopotamus/asciidoctor-epub3/runs/406603429 shows
```
 Test 3h 23m 10s
##[error]The operation was canceled.
Run bundle exec rake spec
  bundle exec rake spec
  shell: C:\Program Files\PowerShell\6\pwsh.EXE -command ". '{0}'"
C:/Users/runneradmin/.rubies/jruby-9.2.9.0/bin/jruby.exe -I'C:/Users/runneradmin/.rubies/jruby-9.2.9.0/lib/ruby/gems/shared/gems/rspec-core-3.9.1/lib';'C:/Users/runneradmin/.rubies/jruby-9.2.9.0/lib/ruby/gems/shared/gems/rspec-support-3.9.2/lib' 'C:/Users/runneradmin/.rubies/jruby-9.2.9.0/lib/ruby/gems/shared/gems/rspec-core-3.9.1/exe/rspec' --pattern 'spec/**{,/*/**}/*_spec.rb' -f progress
..Terminate batch job (Y/N)? 
Terminate batch job (Y/N)? 
##[error]The operation was canceled.
```

**Comment by slonopotamus** [comment]
You can enable timestamps to see that it hangs without any output for several hours.

I also canceled https://github.com/slonopotamus/asciidoctor-epub3/runs/406590333#step:6:4, same thing.

**Comment by eregon** [comment]
So it seems to get stuck after the second dot, i.e. the second spec file.
I think this is a JRuby issue, could you report it to them?

The `Terminate batch job (Y/N)?` is probably caused by cancellation.

To find out which specific spec hangs I would advise to run with `-f documentation`. Then it should show which spec hangs exactly.

**Comment by slonopotamus** [comment]
Ooooh! I didn't notice there are two dots. Thanks, that possibly means that the problem is in my specs.

**Comment by eregon** [comment]
It would still likely be a bug related to JRuby since it works fine on MRI on Windows.
But indeed, worth figuring out which spec exactly hangs.

**Comment by slonopotamus** [comment]
Okay, I [got some progress](https://github.com/slonopotamus/asciidoctor-epub3/runs/406872652#step:6:13), so most likely will be able to fix this myself. Thanks for a great use-ruby-action, btw!

**Comment by eregon** [comment]
Thank you for using it!
Please share if you can when you find the root cause of the issue as it might be useful to others.

**Comment by slonopotamus** [comment]
pygments.rb deadlocks for us when tries to I/O talk to its Python process: asciidoctor/asciidoctor-epub3#253.

Additionally, pygments.rb doesn't pass its own test suite on JRuby: tmm1/pygments.rb#190.

I didn't dig this problem deeper.
